version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: monts
      POSTGRES_USER: monts
      POSTGRES_PASSWORD: monts123
    volumes:
      - ./data:/var/lib/postgresql/data